### ISSUE TITLE
Trader trade changes

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox.io#536] opened 2020-09-05 14:21 UTC
Ideas:
* [x] Randomized starting prices (within a set range).
* ~More trades added the more each trader is traded with.~ (not needed because "reactive pricing and trades" is going to be used instead)
* [x] Add reverse trades (items > gold) for all trades. ~(using the lowest price, to prevent abuse)~
* [x] Reactive pricing and trades. (see second comment below)
* [x] Limited daily stock for each trade.

Possible new trades:
* [x] Tamed mob eggs (rare and expensive trades).
* [x] Marble and granite - alternative to selling them at spawn.
* [x] Seeds/crops - makes sense for traders to have these.
* [x] Ore ~lumps~ or ingots (varying rarity) - spawn sells lumps, but ingots might be okay...
* [x] Mob drops (meat, leather, etc) - not everyone wants to kill animals, and would be great for reverse trades.
* [x] All saplings - another thing not sold at spawn anymore
* [x] All "dirt_with_x" and ore nodes - things that can only be gotten from traders
* [x] Coral and kelp - these are so hard to find when you want them

**Comment by S-S-X** [comment] 2020-09-15 19:09
I like "Randomized prices" idea and think it could be very cheap way to make trading just a bit more interesting, so why not? Can't think of any real reason why not. :+1: 

> Add reverse trades (items > gold) for all trades (using the lowest price, to prevent abuse).

Does it have to be lowest price? It would also make trading more interesting if you could actually gain something by just trading with mobs buying from one and selling to other. I think it could work with randomized prices if there is max amount of single material that one trader would buy and after some cooldown new price is random.

I mean make if it could be so that ~ab~using system actually requires you to go ask current prices so you cannot just set some static profitable trade route.

**Comment by OgelGames** [comment] 2020-09-17 09:13
Another idea I had in regards to the prices, if it's actually possible, is to make the traders change their prices in response to how much they are traded with, similar to how a player would.

Currently I'm thinking it would work like this:

* Traders start with random trades. at random prices. (the "randomized prices" idea above)
* Once a day (say, in the morning, in-game time), each trader would check how much they were traded with over the last day.
* If there were no trades (or very few), nothing would change, so that traders left alone for awhile will not change unexpectedly.
* If there were some trades, prices would increase on the items that were traded a lot, and prices would decrease on the items that were not traded much.

In addition to the changing prices, the trades should also change sometimes, so that once a item's price has been decreased to the lowest price, there will be a chance it will be swapped out for a new trade.

I think these changes would both make the traders more interesting to trade with (bad trades would eventually be replaced by good ones), and limit the profits that can be made by trading items between traders. (prices would slowly change to a point where no profit is made)

**Comment by BuckarooBanzay** [comment] 2020-09-17 17:19
Someday we can even replace the "admin" exchange with traders, i kinda love the stock idea :smile:

**Comment by S-S-X** [comment] 2020-09-18 18:21
> If there were some trades, prices would increase on the items that were traded a lot, and prices would decrease on the items that were not traded much.

Could this use "trade simulation" so that players cannot force some prices down. Simplest it would be similar if trader would lose and gain random stuff from current stock and update prices but for simulation it should not be completely random but based on current stock.
That would make it harder to simply force certain selected item prices down.

**Comment by OgelGames** [comment] 2020-09-21 10:20
So I have implemented the new "trade simulation" functionality, it's not quite ready yet (I think I could optimize a few things), but it is working enough for testing.

I've also moved the fork to github because I think it would be better if it was moved to mt-mods or pandorabox-io, but I'm not sure which...

**Comment by BuckarooBanzay** [comment] 2020-09-22 05:36
> but it is working enough for testing.

"testing" as in: the main server? :smirk: 

> I've also moved the fork to github because I think it would be better if it was moved to mt-mods or pandorabox-io, but I'm not sure which...

I think `pandorabox-io` would fit best as it is server-specific IMO ...

I haven't tested them yet but it looks good :+1: ping me up if you need help with the submodule/git-fu updates

**Comment by OgelGames** [comment] 2020-09-22 06:10
> "testing" as in: the main server? 😏

No, "it's not quite ready yet" 😉  Also I'm changing some more things again... 😄 

> I think `pandorabox-io` would fit best as it is server-specific IMO ...

That's kind of what I was thinking, will move it there and update the `padorabox-mods` submodule url 👍

**Comment by OgelGames** [comment] 2020-09-22 13:54
So I made quite a few changes...

I improved the "trade simulation" by limiting what can be bought with a fixed daily stock that can be defined for each trade, which I think is a lot better that having an unlimited stock, and should allow being more generous with prices and what new trades are added.

I also found a way to get rid of the trader id by storing the trader reference temporarily in a list. (even though storing object references if not recommended, I think is is safe in this case, and so far I have not been able to break it)

And I also moved the trade definitions into a separate file, because I think the new trades should be added there instead of `pandorabox-custom`, as it makes more sense to have them all in one place.

I think that is everything done for the functionality, just need to test it thoroughly (it would be great if it could be updated on the test server), and then add the extra trades...

**Comment by S-S-X** [comment] 2020-09-22 17:55
> I improved the "trade simulation" by limiting what can be bought with a fixed daily stock

I do also think this is very good and straightforward way to make balancing it a lot easier.

> I also found a way to get rid of the trader id

Looked around a bit, yes looks like very nice solution.

> storing object references if not recommended

This is because it is very well possible that object gets removed and id reused by another object so this might be a problem. And if it happens it will be very hard to debug and will easily get closed as "mysterious / can't reproduce" without too much investigation, there will be no useful stack trace.

Seems very good for me, didn't actually test anything but just read through code quickly but still think it is good for trying out.

Maybe could add form or some other identifier name for trader object and check if it exists, then receive fields could check if object is actually trader and then even if someone who's very good at lottery he would just get another trader which should not crash (or can it, did setup function add some required data?).

**Comment by OgelGames** [comment] 2020-09-26 14:38
I finally finished adding all the new trades for the trader, which ended up being 168 in total: https://github.com/pandorabox-io/mobs_npc/blob/trader-rewrite/trader_items.lua 😄 

I added a few "exclusive" trades, including the special dirts, deepstone, ethereal fruit, and ore nodes (with appropriate prices and rarity of course), to make traders more exciting/desirable. IMO I think it's okay to make them available because they don't have any real value beside decoration (and food).

Note that the trades (and prices and stock) can be changed any any time, and all traders will update themselves when they restock, so the "exclusive" trades can be removed or changed at any time if needed 😉 

I will be giving the code some final testing and will merge the code tomorrow, but final decision will of course be the  `pandorabox-mods` PR.

@BuckarooBanzay @S-S-X @SwissalpS

**Comment by S-S-X** [comment] 2020-09-26 15:12
https://github.com/pandorabox-io/mobs_npc/blob/trader-rewrite/trader_items.lua#L119-L120

Maybe rarity should be 70 for these too or even higher? But well I'm not expert with oranges and bananas :)

It is true that those are practically worthless but there's very high collectible value which comes directly from rarity.
What I've seen in game I think that it is very very good that there is few very rare items available, you know players are very happy and excited when they find just few of those worthless items.

**Comment by OgelGames** [comment] 2020-09-26 16:06
> What I've seen in game I think that it is very very good that there is few very rare items available, you know players are very happy and excited when they find just few of those worthless items.

That is a good point, perhaps I should remove those, and keep their value intact... Even if they are rare for traders to have, once they have been found, it will essentially make them unlimited, rather than them being the limited collectables that they are...

**Closed** 2020-09-27 10:32 UTC
Labels: Discussion, enhancement

**Comment by BuckarooBanzay** [comment] 2020-10-01 18:04
too late for the party, but: :tada: nice work
