### ISSUE TITLE
Remove bike mod

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#667] opened 2021-06-05 19:10 UTC
Can we delete mode bike, because as I see many people have problems with it and it useless item ?  Recently one player had bad indecent with bike.

**Comment by S-S-X** [comment] 2021-06-05 20:34
Better copy paste from chat to here so it is clear what "bad incident" was:
> SX: That "bike accident" was that someone found dead player besides bike next to some wall and player was AFK not using respawn button :p

Good to also add this note:
> SX: But bike mod had other problems and have caused few server crashes recently, at least 2 bugs causing crashes are now fixed but nature of mod makes it bit more error prone

**Bike crash issues:** #161 #240 #633 #642
Also we are currently on fork I created to fix another crash (no issue here for this): https://gitlab.com/h2mm/bike/-/issues/11

Bike has caused many problems recently but incident mentioned in description was not "bad incident" but just player either setting that up knowing well how it will look like in game or player going afk either near bike or mounted on bike and the dying.

I saw some players speculating in chat that he lost account and have to create new one because he is permanently dead... well that's not really what happened there 😄

**My opinion about actual removal request:**
Bike is useless, not really needed for anything. Bike also has more problems than just those past server crashes (hopefully fixed now).
Bike however is kind of fun thing even while I've actually used it mostly while testing some problems it has.
I won't be against removal but also would not recommend removal myself just yet.

**Comment by OgelGames** [comment] 2021-06-06 07:17
My opinion is pretty much the same as it was for #463; though it doesn't get used much, it's not completely useless, and I'm sure there would be at least a few players that would complain if it was removed.

**Comment by S-S-X** [comment] 2021-06-06 12:42
I think one good option would be to collect currently known problems with bike like jumpdrive+bike behavior, jumping directly from bike to another thing that attach player and player model scaling to zero issue.
Some of these issues seem to be overlapping a bit and probably partially caused by same parts of code.

Clear list of still broken things as separate bug issues allows easier fixing and testing mod.
I've not tested enough to be able to write clean steps to reproduce each problem, testing things that potentially cause weird behavior with bike would be good.
Some things might not be so obvious in game, wrong player model scaling for example.

All simple server crashes are probably fixed already (but not yet in upstream). There's only one place I can think of where simple crash might still happen and that is tied to server shutdown callback function (not as important and very unlikely to happen but can cause confusing stack traces).

**Comment by S-S-X** [comment] 2021-07-04 23:32
https://gitlab.com/h2mm/bike/-/issues/11 closed by https://gitlab.com/h2mm/bike/-/merge_requests/13
That might fix crash issue, not as direct action what I did with my fork that pandorabox is currently running.
Could switch back to h2mm repo and try it, merged PR apparently also contains many other small fixes.

**Closed** 2021-07-05 04:47 UTC
Labels: question :grey_question:
