### ISSUE TITLE
"Suspiciously large number of objects detected" errors

### ISSUE THREAD

**Issue by BobFred7** [pandorabox-io/pandorabox.io#453] opened 2020-02-23 18:42 UTC
I've noticed a lot of crashes, including the most recent one at the time of this writing, that are logged as `ERROR[Server]: suspiciously large amount of objects detected: n in (x, y, z); removing all of them.`
What causes this? Can this be fixed?
Several instances of this:
```
2020-02-12 10:09:56: ERROR[Server]: suspiciously large amount of objects detected: 72 in (-181,0,158); removing all of them.

2020-02-12 10:19:13: ERROR[Server]: suspiciously large amount of objects detected: 76 in (1356,0,-1369); removing all of them.
2020-02-12 10:19:13: ERROR[Server]: suspiciously large amount of objects detected: 87 in (1357,0,-1368); removing all of them.

2020-02-15 20:16:28: ERROR[Server]: suspiciously large amount of objects detected: 84 in (-218,-1,-5); removing all of them.
2020-02-15 20:16:45: ERROR[Server]: suspiciously large amount of objects detected: 84 in (-218,-1,-5); removing all of them.
2020-02-15 20:16:55: ERROR[Server]: suspiciously large amount of objects detected: 75 in (-218,0,-5); removing all of them.
2020-02-15 20:16:57: ERROR[Server]: suspiciously large amount of objects detected: 69 in (-219,-1,-4); removing all of them.
2020-02-15 20:17:14: ERROR[Server]: suspiciously large amount of objects detected: 70 in (-155,3,233); removing all of them.

2020-02-15 20:16:45: ERROR[Server]: suspiciously large amount of objects detected: 84 in (-218,-1,-5); removing all of them.
2020-02-15 20:16:55: ERROR[Server]: suspiciously large amount of objects detected: 75 in (-218,0,-5); removing all of them.
2020-02-15 20:16:57: ERROR[Server]: suspiciously large amount of objects detected: 69 in (-219,-1,-4); removing all of them.
2020-02-15 20:17:14: ERROR[Server]: suspiciously large amount of objects detected: 70 in (-155,3,233); removing all of them.
2020-02-15 20:17:59: ERROR[Server]: suspiciously large amount of objects detected: 85 in (-1251,630,-1263); removing all of them.
2020-02-15 20:17:59: ERROR[Server]: suspiciously large amount of objects detected: 200 in (-1250,630,-1263); removing all of them.
2020-02-15 20:17:59: ERROR[Server]: suspiciously large amount of objects detected: 80 in (-1250,630,-1262); removing all of them.
2020-02-15 20:17:59: ERROR[Server]: suspiciously large amount of objects detected: 84 in (-1250,631,-1263); removing all of them.
2020-02-15 20:17:59: ERROR[Server]: suspiciously large amount of objects detected: 128 in (-1250,631,-1262); removing all of them.

2020-02-15 22:38:11: ERROR[Server]: suspiciously large amount of objects detected: 79 in (10,975,55); removing all of them.
```

**Comment by OgelGames** [comment] 2020-02-24 02:04
These are not crashes, just errors/warnings about the server removing entities. As far as I know they are added to the crash logs because any line with `ERROR[Server]` is logged there.

I think it could be partially fixed by increasing the `max_objects_per_block` setting, but that only lessens the removal and errors, not the cause, which I suspect is clogged pipeworks tubes.

**Comment by BuckarooBanzay** [comment] 2020-02-29 13:53
@BobFred7 those messages are originating from here:

https://github.com/minetest/minetest/blob/0c08f948d7014e66d5a79d7584c03164af2edd93/src/serverenvironment.cpp#L1820

As OgelGames said: those are just warnings most likely caused by burst tubes...

Closing this as we have other more critical bugs, feel free to write here if you still have questions...

**Closed by BuckarooBanzay** 2020-02-29 13:53 UTC
Labels: question :grey_question:
