### ISSUE TITLE
Interrupted digtron during long tunneling

### ISSUE THREAD

**Issue by kubaorlen** [pandorabox-io/pandorabox.io#412] opened 2020-01-14 15:03 UTC
During long tunneling, digtron often stop working. Control module is interrupted, fuel and inventory storage can't be open. Probably the reason is faster digtron movement than mapgen working. Maybe digtron should stop working when nearest mapgen is working, to avoid lost inventory stuff.

**Comment by kiedtl** [comment] 2020-01-14 20:45
This also happened to me. digtron suddenly stopped while boring down, and fuel/inventory storages couldn't be opened, neither could digtron nodes be moved or selected.

**Comment by OgelGames** [comment] 2020-01-15 01:46
> Maybe digtron should stop working when nearest mapgen is working, to avoid lost inventory stuff.

Looks like it already does: https://github.com/minetest-mods/digtron/blob/master/util_execute_cycle.lua#L48

**Comment by thomasrudin** [comment] 2020-01-15 14:31
Those are sadly engine issues:
https://github.com/minetest/minetest/issues/8067

No one came up with a reliable reproduction of the bug, so i don't think this will get fixed soon.. :confounded: 

But FaceDeer is working on another big rework of the digtron mod:
https://github.com/minetest-mods/digtron/tree/digtron-2.0-digpocalypse

This should fix a lot of bugs hopefully :smile:

**Comment by BuckarooBanzay** [comment] 2020-03-24 14:55
> to avoid lost inventory stuff.

This is caused by the famous engine-issue and happens frequently with the digtron mod (also the jumpdrive mod now and then)

Upstream issue: https://github.com/minetest/minetest/issues/8067
Related: #431

Closing here, clues/repros please in the upstream issue..

**Closed by BuckarooBanzay** 2020-03-24 14:55 UTC
Labels: bug :beetle:
