### ISSUE TITLE
Bug in craft guide 

### ISSUE THREAD

**Issue by Emil9736** [pandorabox-io/pandorabox.io#635] opened 2021-03-30 17:19 UTC
Colour quadrats instead of icons for some items, which require fro their crafting rubber fiber. 
![bug 1](https://user-images.githubusercontent.com/53637630/113029460-e6a2ea80-91a5-11eb-855b-e2fb66bfa586.png)
![bug 2](https://user-images.githubusercontent.com/53637630/113029464-e86cae00-91a5-11eb-8879-8821716e9a6e.png)

**Comment by OgelGames** [comment] 2021-03-31 02:07
Those are the recipes from the bike mod, which has been disabled temporarily due to a bug: #633

Should be fixed after the next server restart.

**Closed** 2021-03-31 02:08 UTC
Labels: invalid

**Comment by Emil9736** [comment] 2021-03-31 07:47
> Should be fixed after the next server restart.
But server was not restarted, so this issue is valid. Please change label **invalid**

**Comment by SwissalpS** [comment] 2021-03-31 07:54
The version of the mod repo is truth :)

**Comment by Emil9736** [comment] 2021-03-31 08:31
> No need to have multiple threads going for single cause.

In that case, we should hide items of unrepaired mode. Nobody see this issues = nobody create multiple threads for single cause.

**Comment by S-S-X** [comment] 2021-03-31 08:34
Technically I think this is known issue with deployment and has label "immediate restart needed" in mods repo. I believe this was caused by updating mods repo at the same moment when server deployment started.

So I think this is what happened: deployment started and mods got loaded + recipes registered, immediately after that bike mod was deleted but it was already loaded and resides in lua vm memory. However textures cannot be loaded anymore as they do not exist.

This would be either duplicate or enhancement for deployment. Probably this belongs to "acceptable known problems" category so let's mark this as duplicate.

**Comment by OgelGames** [comment] 2021-03-31 12:39
My reasoning for marking it invalid was that it's not a bug in any mod, it's just the way Minetest handles textures.

Maybe a "not a bug" (or simmilar) label would be better...

**Comment by SwissalpS** [comment] 2021-03-31 17:06
or just a "yes, sometimes it rains" tag :p
