### ISSUE TITLE
Server crash on /tp request when in a travelbox.

### ISSUE THREAD

**Issue by Soviet-Glider** [pandorabox-io/pandorabox.io#393] opened 2019-12-29 20:09 UTC
First the glass and tin doors of travelbox mod are now unknow nodes. So when I signalized the situation, and accepted a /tpr request from another play while I was struck in my travelbox the server crashed. To be sure it was the source of the problem, we retry the move, but instead this time I send a /tphr to the same player while struck in the travelbox, crash happen again. Some weeks ago another  player send me a /tphr request because struck in one of my private travelbox with an iron door, I accept it and no crash occured.

**Comment by thomasrudin** [comment] 2019-12-29 20:45
> First the glass and tin doors of travelbox mod are now unknow nodes

That may be introduced here: https://github.com/pandorabox-io/pandorabox-mods/commit/b63ddc1ab8a651d748fb193272f9bbd2541af231
I'm reverting it until the issue there is found/fixed

The other crash from the `teleport-request` mod needs to be investigated further:
```
2019-12-29 19:17:22: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'tpr' in callback on_chat_message(): /data/world//worldmods/tpr/init.lua:50: attempt to index a nil value
2019-12-29 19:17:22: ERROR[Main]: stack traceback:
2019-12-29 19:17:22: ERROR[Main]: 	/data/world//worldmods/tpr/init.lua:50: in function 'find_free_position_near'
2019-12-29 19:17:22: ERROR[Main]: 	/data/world//worldmods/tpr/init.lua:274: in function 'func'
2019-12-29 19:17:22: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/chat.lua:55: in function </usr/local/share/minetest/builtin/game/chat.lua:34>
```

**Comment by OgelGames** [comment] 2019-12-30 07:58
The crash was caused by this line: https://github.com/ChaosWormz/teleport-request/blob/06c076a8857124023d8d2a0e49779cd048df7c79/init.lua#L83, which doesn't check if the node is registered before checking if it is walkable.

I have opened a PR to fix it here: https://github.com/ChaosWormz/teleport-request/pull/20

**Comment by OgelGames** [comment] 2020-01-01 09:10
PR has been merged, was going to update the mod repo, but I noticed there is a PR for it that has not been merged (pandorabox-io/pandorabox-mods#213), so not sure what is happening with that... 😕

**Comment by thomasrudin** [comment] 2020-01-01 18:26
> but I noticed there is a PR for it that has not been merged

I haven't tested it but there was an issue with teleport-sniping if i remember correctly...

**Comment by BobFred7** [comment] 2020-01-01 19:08
What's teleport-sniping?

**Comment by thomasrudin** [comment] 2020-01-02 11:53
> What's teleport-sniping?

I think the `/tpr`'s did'nt timeout and a `/tpy` from the other player could have been executed at any time (not sure anymore though, was some time ago... :rofl:)

**Comment by Panquesito7** [comment] 2020-01-03 01:10
> I think the `/tpr`'s didn't timeout and a `/tpy` from the other player could have been executed at any time

@thomasrudin, AFAIK, that bug was fixed many time ago. 🙂

**Comment by thomasrudin** [comment] 2020-01-06 07:08
fixed by https://github.com/pandorabox-io/pandorabox-mods/pull/297

**Closed by thomasrudin** 2020-01-06 07:08 UTC
Labels: Fixed, crash :face_with_head_bandage:
