### ISSUE TITLE
Hazmat/Radiation not working

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#290] opened 2019-08-22 15:26 UTC
Since the new update of the engine the hazmat armor does not seem to work anymore

**Comment by coil0** [comment] 2019-08-22 22:18
Fixed by minetest-mods/technic#509. The change was caused by the engine update that added [4d7f2967172c5a358811ac1f24115b281eff2431](/pandorabox-io/minetest/commit/4d7f2967172c5a358811ac1f24115b281eff2431).

**Comment by thomasrudin** [comment] 2019-08-23 05:13
thx coil, you are awesome :+1:

**Closed** 2019-08-23 05:42 UTC
Labels: bounty: 20k minegeld, bug
