### ISSUE TITLE
Hangglider protection message spamming

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox.io#377] opened 2019-12-16 15:17 UTC
When flying through an area, without flak, owned by another player, the chat is spammed with messages.
I have failed to reproduce on my test-server. Only see this on pandorabox.io

**Comment by thomasrudin** [comment] 2019-12-16 16:27
> Only see this on pandorabox.io

interesting :confused:

**Comment by OgelGames** [comment] 2019-12-17 10:36
I was able to replicate it on my test server; it only happens when in an area protected by a protection block, not for those protected by `areas`.

The spam is caused by this call to `minetest.is_protected()`: https://notabug.org/Piezo_/minetest-hangglider/src/master/init.lua#L155, and the messages come from here: https://notabug.org/TenPlus1/protector/src/master/init.lua#L239

Not quite sure how to fix it though, other than adding a timer so that the message is sent less often, just to get rid of the spamming.

**Comment by thomasrudin** [comment] 2019-12-17 11:56
I'm not sure about a solution either but IMO the chat message is a very weird side-effect for a function that should *just* check the protection... :/

Maybe a third parameter in `minetest.is_protected()` that specifies the log level or something but that feels hacky and involves changing engine code if done properly.

**Comment by thomasrudin** [comment] 2019-12-17 12:38
Upstream issue: https://notabug.org/TenPlus1/protector/issues/17

**Comment by int-ua** [comment] 2019-12-24 04:47
Using a public workshop machines is also affected.

**Comment by BobFred7** [comment] 2019-12-27 18:40
I don't think flak is actually used much on this server, so maybe we could cut out hangglider init.lua lines 155 to 163 as a temporary solution while we wait for TenPlus1 to deal with the flaws in protector?

**Comment by thomasrudin** [comment] 2019-12-28 19:01
> I don't think flak is actually used much on this server, so maybe we could cut out hangglider init.lua lines 155 to 163 as a temporary solution while we wait for TenPlus1 to deal with the flaws in protector?

I'd rather like to fix the `protector` mod instead with the above solution, lets see it Tenplus1 sees the issue...

**Comment by BobFred7** [comment] 2019-12-29 18:52
> > temporary solution

> > while we wait for TenPlus1

But okay

**Comment by S-S-X** [comment] 2020-02-05 20:39
Removed "waiting" label as this can be now fixed at https://github.com/S-S-X/protector repo and can try to merge stuff to upstream later.

**Comment by thomasrudin** [comment] 2020-02-06 06:58
> Removed "waiting" label as this can be now fixed at https://github.com/S-S-X/protector repo and can try to merge stuff to upstream later.

@tenplus1 is aware of the issue by the way: https://notabug.org/TenPlus1/protector/issues/19

I hope we can merge that upstream again some day...

**Comment by thomasrudin** [comment] 2020-02-13 12:54
@S-S-X i created a PR with your commits for the protector-tool registration: https://notabug.org/TenPlus1/protector/pulls/20

Let's see if/how 10+1 responds...

**Closed** 2020-02-13 13:04 UTC
Labels: bug :beetle:
