### ISSUE TITLE
Wiki caching issues

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#406] opened 2020-01-11 20:38 UTC
```
noticed thing about wiki, it seems that categories have not been updated unless I'm logged in
so seems to be some caching problem if logging in bypasses some caching.
Am I doing something wrong or wiki backround jobs not running correctly?
```

@S-S-X

**Comment by S-S-X** [comment] 2020-01-21 16:56
Could be caused by same root issue but also noticed that updating pictures has similar problem:

1. upload picture
2. upload new version of that picture -> wiki displays old picture in place of new version
3. revert update ->wiki reverts to old picture and shows correct updated for 2nd version (uploaded in step 2.)
4. revert again to pic that seems to be correct -> revert happens and 2nd pic is again same that you originally uploaded at step 1

Worked around this issue by uploading new file and updating wiki page to use that new file.

**Comment by thomasrudin** [comment] 2020-01-26 17:19
> 2. upload new version of that picture -> wiki displays old picture in place of new version

I'm having trouble reproducing this, worked for me in my example (https://pandorabox.io/wiki/index.php/File:Screenshot_20200120_211946.png) on the first try :confused: 

Even a second window in private mode showed the correct version....

**Comment by S-S-X** [comment] 2020-01-26 21:07
Google Chrome 79.0.3945.117 was used.
File was this one: https://pandorabox.io/wiki/index.php/File:Digiline_piston_setup.png

**Comment by thomasrudin** [comment] 2020-02-01 16:43
I managed to reproduce this: https://pandorabox.io/wiki/index.php/File:Screenshot_20200120_211946.png

Now i need to find the actual problem :smile:

**Comment by thomasrudin** [comment] 2020-02-06 07:14
@S-S-X can you re-test this again, works for me, i added a few cache-bust headers:

```
Header set Cache-Control "max-age=600, must-revalidate"
```

And enabled opcode caching: https://github.com/thomasrudin/php-docker/commit/e461d30a1831ba518b9e046d8996d0b56fe1b2d4

**Comment by BuckarooBanzay** [comment] 2020-03-02 10:17
closing this, didn't have any problem and the repro works now.

Feel free to reopen if the problem persists...

**Comment by S-S-X** [comment] 2021-09-17 14:50
> specing Hedgehog: nope, nothing in Category:Events
> Hedgehog Odd, I see it there ....

Checked situation with wiki and similar issue, caching stuck server side and category wont update for user who are not logged in.
Also to be clear it is not browser caching that causes this but server side caching.

Wiki caches pages server side to be able to serve more clients without rendering and resolving all the stuff again for every request, this caching is disabled for logged in users and logged in users will get correct results but users who have not logged in see old page.

Looked around a bit and found this, that's most probably what causes these problems https://phabricator.wikimedia.org/T26575
(also https://www.mediawiki.org/wiki/Topic:Ta3n8f4l49wuqe9s)

There seems to be some patch available but if it seems complicated I think it might not be worth fixing, purging page/category that has problems will rebuild caches but also that's manual work and somebody has to do / know it.

**Comment by BuckarooBanzay** [comment] 2021-09-17 15:30
The page not showing up in Events if the PixelArtContest2021, right? (https://pandorabox.io/index.php/PixelArtContest2021)
(i need some data to reproduce this reliably)

Currently i'm having this when i'm logged in and also in a private browser window:

![Screenshot_2021-09-17_17-27-59](https://user-images.githubusercontent.com/39065740/133811488-b90f49f0-2880-49eb-a3b3-119487197ad9.png)

I _could_ flush the cashes but that won't solve the underlying problem...

**Comment by S-S-X** [comment] 2021-09-17 15:51
> The page not showing up in Events if the PixelArtContest2021, right? (https://pandorabox.io/index.php/PixelArtContest2021)
> (i need some data to reproduce this reliably)
> 
> Currently i'm having this when i'm logged in and also in a private browser window:
> 
> ![Screenshot_2021-09-17_17-27-59](https://user-images.githubusercontent.com/39065740/133811488-b90f49f0-2880-49eb-a3b3-119487197ad9.png)
> 
> I _could_ flush the cashes but that won't solve the underlying problem...

I did purge caches for that category page when I noticed issue, why I opened this was more about possibly fixing underlying problem because it happened multiple times. Not really too often but is annoying if you add pages and then go advertise changes but other people still sees old stuff.

**Comment by BuckarooBanzay** [comment] 2021-09-17 17:37
Disabled the file-cache here: https://github.com/pandorabox-io/pandorabox.io/commit/4ace545c0ad1f6e008d82006d532b5053c615895
There is still an object caching enabled with
```php
$wgMainCacheType = CACHE_ANYTHING;
```
A memcache server would be ideal but lets not overdo it, page responses look good so far

The upstream issue here (https://phabricator.wikimedia.org/T26575) looks spot-on, thanks for looking that up.
Not sure what to think of the mw codebase though when i read stuff like this:
```
I think you're radically under-estimating how deeply scary anything related to the
Squid/Varnish/ATS CDN caching layer is. This would not remotely be a suitable first bug.
```

Closing this, please reopen if it persists

**Closed by BuckarooBanzay** 2021-09-17 17:37 UTC
Labels: bug :bug:, Wiki
